//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVELOPER
    {
        public int ID { get; set; }
        public int AID { get; set; }
        public string FNAME { get; set; }
        public string LNAME { get; set; }
        public string PHONE { get; set; }
        public string EMAIL { get; set; }
        public int pid { get; set; }
    
        public virtual ADVISOR ADVISOR { get; set; }
        public virtual Project Project { get; set; }
    }
}
